local:
  rootpath: ''
  rootpath_atlas: ""
  model_path:  "sam2/checkpoints/sam2.1_hiera_large.pt"
  num_workers: 0
  device: "cpu"

cluster:
  rootpath: ""  
  model_path:  "sam2/checkpoints/sam2.1_hiera_large.pt"
  num_workers: 96
  device: "cuda"
  

constants:
  scale: 40/63 # the scaling factor between BF and FISH microscopy
  max_dist: 60 # The maximum distance between two cells for the matching of BF and FISH
  size_radius: 60 # The radius for computing the indivudal videos of individual cells
  backward: True # If the segmentation is done for the last frame: propagate with SAM2 backwardly
  
experiment:
  exp_path: '2025-10-13_exp/'
  condition: '1-NA' # or 2-MIX, 3-24H, 4-24H
  genes: ["GZMB", "TNF", "CD69","IFNG",  "CCR7", "CD8", "GBP4", "IL2RA",  "XP01", "IRF8",  "ACTB", "CORO1A"] 
  rounds: [0,1,2,3,4,5]
  n_features_dim: 100
